name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          # this should be all major platforms and any native target that is marked as "regularly tested"
          # see: https://kotlinlang.org/docs/native-target-support.html
          - target: jvmTest
            os: ubuntu-latest
          - target: jsTest
            os: ubuntu-latest
          - target: wasmJsTest
            os: ubuntu-latest
          - target: wasmWasiTest
            os: ubuntu-latest
          - target: macosX64Test
            os: macos-latest
          - target: macosArm64Test
            os: macos-latest
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: iosX64Test
            os: macos-latest
          - target: linuxX64Test
            os: ubuntu-latest
          - target: watchosSimulatorArm64Test
            os: macos-latest
          - target: watchosX64Test
            os: macos-latest
          - target: tvosSimulatorArm64Test
            os: macos-latest
          - target: tvosX64Test
            os: macos-latest
          - target: mingwX64Test
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run tests with Gradle
        run: ./gradlew ${{ matrix.target }}
